name = "GamePieces"
uuid = "cc4a5a68-64ec-4a9a-b5d6-4af0620d7f4a"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
